Algoritmo "calculadora"

Var
n1,n2,soma,subtracao,multiplicacao,divisao : real
Inicio
escreva("Digite o primeiro número: ")
leia(n1)
escreva("Digite o segundo número: ")
leia(n2)
soma=n1+n2
leia(soma)
subtracao=n1-n2
leia(subtracao)
multiplicacao=n1*n2
leia(multiplicacao)
divisao=n1/n2
leia(divisao)
escreva(n1,"+",n2,"=",soma)
escreva(n1,"-",n2,"=",subtracao)
escreva(n1,"×",n2,"=",multiplicacao)
escreva(n1,"÷",n2,"=",divisao)
Fimalgoritmo